### ISSUE TITLE
Distinction between '100%' and 'full'?

### ISSUE THREAD

**Issue by FLHerne** [tpfanco/tpfanco-admin#1]
I would have expected these to be synonymous, but on my T420s these equate to 4850rpm and 5450rpm respectively. The former isn't high enough to prevent overheating (hard shutdown at 98°C) under load.

Is this intended to be the case? If so, I couldn't find any documentation of it.

Thanks for the software, it really helps keep the noise down under normal usage.

**Comment by vsht** [comment]
100% corresponds to setting

```
echo level 7 > /proc/acpi/ibm/fan
```

while full is the same as

```
echo level disengaged > /proc/acpi/ibm/fan
```

for more information have a look at
http://www.thinkwiki.org/wiki/How_to_control_fan_speed#For_Linux

**Comment by FLHerne** [comment]
Thanks for the info!
